Repository microsoft/PullRequestQuantifier, pull requests merged in 2021-03, with the labels that each got.

#144 Batch during insertion to blob
  src/PullRequestQuantifier.Common/Azure/BlobStorage/BlobStorage.cs
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/Program.cs
Labels: Extra Small

#147 Activate EnforceCodeStyleInBuild in some projects that were left out
  src/Clients/PullRequestQuantifier.Client.Tests/PullRequestQuantifier.Client.Tests.csproj
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/PullRequestQuantifier.GitHub.Client.Tests.csproj
  src/Clients/PullRequestQuantifier.GitHub.Client/PullRequestQuantifier.GitHub.Client.csproj
  src/Clients/PullRequestQuantifier.VsCode.Client/PullRequestQuantifier.VsCode.Client.csproj
  src/PullRequestQuantifier.Abstractions.Tests/PullRequestQuantifier.Abstractions.Tests.csproj
  src/PullRequestQuantifier.Common.Tests/PullRequestQuantifier.Common.Tests.csproj
  src/PullRequestQuantifier.Common/PullRequestQuantifier.Common.csproj
  src/PullRequestQuantifier.GitEngine.Tests/PullRequestQuantifier.GitEngine.Tests.csproj
  src/PullRequestQuantifier.GitEngine/PullRequestQuantifier.GitEngine.csproj
  src/Tools/PullRequestQuantifier.Tools.CloneAdoRepo/PullRequestQuantifier.Tools.CloneAdoRepo.csproj
  src/Tools/PullRequestQuantifier.Tools.Common/PullRequestQuantifier.Tools.Common.csproj
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/PullRequestQuantifier.Tools.QuantifyRepositories.csproj
Labels: No Changes

#148 Compare diff only against first parent
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/Program.cs
Labels: Extra Small

#149 Move mustache templates under mustache folder
  src/Clients/PullRequestQuantifier.Client/Extensions/Mustache/ConsoleOutput.mustache
  src/Clients/PullRequestQuantifier.Client/Extensions/Mustache/QuantifierComment.mustache
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierResultExtensions.cs
  src/Clients/PullRequestQuantifier.Client/PullRequestQuantifier.Client.csproj
  src/Clients/PullRequestQuantifier.VsCode.Client/PullRequestQuantifier.VsCode.Client.csproj
Labels: Extra Small

#150 Fix mustache template email title
  src/Clients/PullRequestQuantifier.Client/Extensions/Mustache/QuantifierComment.mustache
Labels: No Changes

#151 Use shield badge for comment title
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifierResultExtensionsTests.cs
  src/Clients/PullRequestQuantifier.Client/Extensions/Mustache/QuantifierComment.mustache
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierResultExtensions.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/PullRequestEventHandler.cs
Labels: Extra Small

#152 Code coverage improvement part1
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifyClientHelperTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Data/InstallationPayload.txt
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Data/InstallationRepositories.txt
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Data/PulRequestPayload.txt
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Events/InstallationEventHandlerTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Events/InstallationRepositoriesEventHandlerTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Events/PullRequestEventHandlerTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/PullRequestQuantifier.GitHub.Client.Tests.csproj
  src/Clients/PullRequestQuantifier.GitHub.Common/GitHubClient/Exceptions/CreateGitHubClientException.cs
  src/Clients/PullRequestQuantifier.GitHub.Common/GitHubClient/GitHubClientAdapter.cs
  src/Clients/PullRequestQuantifier.GitHub.Common/Models/InstallationEventPayload.cs
  src/Clients/PullRequestQuantifier.GitHub.Common/Models/InstallationRepositoriesEventPayload.cs
  src/PullRequestQuantifier.Common.Tests/ArgumentCheckTests.cs
  src/PullRequestQuantifier.Common.Tests/FileSystemExtensionsTests.cs
  src/PullRequestQuantifier.Common/Azure/BlobStorage/AzureBlobSettings.cs
  src/PullRequestQuantifier.Common/Azure/BlobStorage/BlobStorage.cs
  src/PullRequestQuantifier.Common/Azure/ServiceBus/AzureServiceBus.cs
  src/PullRequestQuantifier.Common/Azure/ServiceBus/AzureServiceBusSettings.cs
  src/PullRequestQuantifier.Common/Azure/Telemetry/AppInsightsExtensions.cs
  src/PullRequestQuantifier.Common/Azure/Telemetry/AppTelemetry.cs
  src/PullRequestQuantifier.Common/Azure/Telemetry/OperationScope.cs
  src/PullRequestQuantifier.Repository.Service/appsettings.Development.json
Labels: Large

#153 Repository service get PR lead time
  src/Clients/PullRequestQuantifier.GitHub.Common/GitHubClient/GitHubClientAdapter.cs
  src/Clients/PullRequestQuantifier.GitHub.Common/GitHubClient/IGitHubClientAdapter.cs
  src/PullRequestQuantifier.Repository.Service/Events/InstallationEventHandler.cs
  src/PullRequestQuantifier.Repository.Service/Models/CommitStats.cs
  src/PullRequestQuantifier.Repository.Service/Models/CommitStatsMap.cs
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/Program.cs
Labels: Small

#154 Deploy repo service to azure
  .github/workflows/repository_service.yml
  src/PullRequestQuantifier.Common/Azure/ServiceBus/AzureServiceBus.cs
  src/PullRequestQuantifier.Repository.Service/Events/InstallationEventHandler.cs
Labels: Small

#155 More code coverage improvement part2 and fix a bug into the context generator
  PullRequestQuantifier.sln
  src/Clients/PullRequestQuantifier.Client.Tests/ContextGeneratorTests.cs
  src/Clients/PullRequestQuantifier.Client/ContextGenerator/ContextGenerator.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Program.cs
  src/Clients/PullRequestQuantifier.GitHub.Common.Tests/GitHubClientAdapterFactoryTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Common.Tests/GitHubEventHostTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Common.Tests/PullRequestQuantifier.GitHub.Common.Tests.csproj
  src/Clients/PullRequestQuantifier.GitHub.Common/Events/GitHubEventHost.cs
  src/PullRequestQuantifier.Abstractions/Context/Context.cs
Labels: Medium

#156 Add multi os support to vscode extension
  src/Clients/PullRequestQuantifier.VsCode.Client/PullRequestQuantifier.VsCode.Client.csproj
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/src/extension.ts
Labels: Extra Small

#157 Add images to vscode readme
  src/Clients/PullRequestQuantifier.VsCode.Client/PullRequestQuantifier.VsCode.Client.csproj
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/README.md
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/package.json
Labels: Extra Small

#158 Change some Vscode settings and service bus transport type
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/1ES.png
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/package-lock.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/package.json
  src/PullRequestQuantifier.Common/Azure/ServiceBus/AzureServiceBus.cs
Labels: Extra Small

#159 Update vscode readme
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/README.md
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/package.json
Labels: Extra Small

#160 Add requirements.txt to default ignored files
  src/Clients/PullRequestQuantifier.Client/ContextGenerator/DefaultContext.cs
Labels: Extra Small

#161 Add github workflow for vscode extension
  .github/workflows/vscode_client.yml
  src/Clients/PullRequestQuantifier.VsCode.Client/PullRequestQuantifier.VsCode.Client.csproj
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/package-lock.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/package.json
Labels: Extra Small

#163 Always use ubuntu 18-04
  .github/workflows/build_net_core.yml
Labels: Extra Small

#162 feat: add yarn.lock to default ignored files
  src/Clients/PullRequestQuantifier.Client/ContextGenerator/DefaultContext.cs
Labels: Extra Small

#164 Remove great job and lower size limit
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifierResultExtensionsTests.cs
  src/Clients/PullRequestQuantifier.Client/Extensions/Mustache/QuantifierComment.mustache
Labels: Extra Small

#165 Use Yellow instead of DarkYellow, since DarkYellow is not defined into shields.io
  src/Clients/PullRequestQuantifier.Client/ContextGenerator/DefaultContext.cs
Labels: Extra Small
