Repository microsoft/PullRequestQuantifier, pull requests merged in 2021-02, with the labels that each got.

#86 Pull request quantifier: add a tool to quantify all commits into a repo and output the results to a CSV
  PullRequestQuantifier.sln
  src/Tools/PullRequestQuantifier.Tools.CloneAdoRepo/Program.cs
  src/Tools/PullRequestQuantifier.Tools.CloneAdoRepo/PullRequestQuantifier.Tools.CloneAdoRepo.csproj
  src/Tools/PullRequestQuantifier.Tools.Common/CommandLine.cs
  src/Tools/PullRequestQuantifier.Tools.Common/PullRequestQuantifier.Tools.Common.csproj
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/Program.cs
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/Properties/launchSettings.json
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/PullRequestQuantifier.Tools.QuantifyRepositories.csproj
Labels: Medium

#87 Add comment markdown options
  src/Clients/PullRequestQuantifier.Client.Tests/Data/AssertCommentSummaryCollapsed.txt
  src/Clients/PullRequestQuantifier.Client.Tests/Data/AssertCommentSummaryNotCollapsed.txt
  src/Clients/PullRequestQuantifier.Client.Tests/DefaultContextTests.cs
  src/Clients/PullRequestQuantifier.Client.Tests/PullRequestQuantifier.Client.Tests.csproj
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifierResultExtensionsTests.cs
  src/Clients/PullRequestQuantifier.Client/Extensions/MarkdownCommentOptions.cs
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierComment.mustache
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierResultExtensions.cs
Labels: Medium

#89 Add initial VSCode client
  PullRequestQuantifier.sln
  src/Clients/PullRequestQuantifier.VsCode.Client/Program.cs
  src/Clients/PullRequestQuantifier.VsCode.Client/PullRequestQuantifier.VsCode.Client.csproj
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/.eslintrc.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/.gitignore
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/.vscode/extensions.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/.vscode/launch.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/.vscode/settings.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/.vscode/tasks.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/.vscodeignore
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/1ES.png
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/CHANGELOG.md
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/README.md
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/package-lock.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/package.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/src/extension.ts
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/src/test/runTest.ts
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/src/test/suite/extension.test.ts
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/src/test/suite/index.ts
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/tsconfig.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/vsc-extension-quickstart.md
Labels: Large

#92 Exclude "packages.lock.json" in the default context
  src/Clients/PullRequestQuantifier.Client/ContextGenerator/DefaultContext.cs
Labels: Extra Small

#94 Change default thresholds
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifyClientTests.cs
  src/Clients/PullRequestQuantifier.Client/ContextGenerator/DefaultContext.cs
Labels: Extra Small

#95 Add coverage action on windows workflow
  .github/workflows/build_net.yml
Labels: Extra Small

#96 Block parameter less GitFilePatch constructor and force to use one with the required params
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/GitHubEventHost.cs
  src/PullRequestQuantifier.Abstractions/Git/GitFilePatch.cs
  src/PullRequestQuantifier.GitEngine/GitEngine.cs
Labels: Extra Small

#105 Create a new service for PullRequestQuantifier.Feedback.Service, ( next will add auth and deployment to azure)
  PullRequestQuantifier.sln
  prquantifier.yaml
  src/PullRequestQuantifier.Common/Azure/BlobStorage/BlobStorage.cs
  src/PullRequestQuantifier.Common/Azure/BlobStorage/IBlobStorage.cs
  src/PullRequestQuantifier.Common/PullRequestQuantifier.Common.csproj
  src/PullRequestQuantifier.Feedback.Service/Controllers/FeedbackController.cs
  src/PullRequestQuantifier.Feedback.Service/Models/FeedbackModel.cs
  src/PullRequestQuantifier.Feedback.Service/Program.cs
  src/PullRequestQuantifier.Feedback.Service/PullRequestQuantifier.Feedback.Service.csproj
  src/PullRequestQuantifier.Feedback.Service/README.md
  src/PullRequestQuantifier.Feedback.Service/Registrar.cs
  src/PullRequestQuantifier.Feedback.Service/Startup.cs
Labels: Large

#106 Add github app tests using test server
  PullRequestQuantifier.sln
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Controllers/Data/TestGitHubWebhook1.json
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Controllers/GitHubWebhookEndpointTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/PullRequestQuantifier.GitHub.Client.Tests.csproj
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/ConfigurationBuilderExtensions.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/GitHubClientTestServer.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/InMemoryEventBus.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/ObjectExtensions.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Controllers/GitHubWebhookController.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Models/AcceptedGitHubActionTypes.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Models/AcceptedGitHubEventTypes.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Models/GitHubEventActions.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Registrar.cs
Labels: Large, client: github

#107 Add telemetry for github events
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/InMemoryEventBus.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Controllers/GitHubWebhookController.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/AzureServiceBus.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/GitHubEventHost.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/IEventBus.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/IGitHubEventHandler.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/InstallationEventHandler.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/PullRequestEventHandler.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Models/GitHubEventActions.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Registrar.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/appsettings.json
Labels: Large, client: github

#111 Use short output in VSCode client
  docs/images/client-vscode-moreinfo.png
  docs/images/client-vscode-status.png
  src/Clients/PullRequestQuantifier.Client/Extensions/ConsoleOutput.mustache
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierResultExtensions.cs
  src/Clients/PullRequestQuantifier.Client/PullRequestQuantifier.Client.csproj
  src/Clients/PullRequestQuantifier.Local.Client/Program.cs
  src/Clients/PullRequestQuantifier.VsCode.Client/PullRequestQuantifier.VsCode.Client.csproj
  src/Clients/PullRequestQuantifier.VsCode.Client/README.md
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/package-lock.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/package.json
  src/Clients/PullRequestQuantifier.VsCode.Client/pull-request-quantifier/src/extension.ts
Labels: Small, client: vscode

#112 Extend Github client settings to accommodate any GHAE flavor
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifyClientTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Controllers/Data/TestGitHubWebhook1.json
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Controllers/GitHubWebhookEndpointTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/GitHubClientTestServer.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/InMemoryEventBus.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Controllers/GitHubWebhookController.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/IEventBus.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/PullRequestEventHandler.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/GitHubClient/GitHubAppFlavorSettings.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/GitHubClient/GitHubClientAdapterFactory.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/GitHubClient/IGitHubClientAdapterFactory.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/PullRequestQuantifier.GitHub.Client.csproj
  src/Clients/PullRequestQuantifier.GitHub.Client/Registrar.cs
  src/PullRequestQuantifier.Feedback.Service/AppConfiguration.cs
  src/PullRequestQuantifier.Feedback.Service/Controllers/FeedbackController.cs
  src/PullRequestQuantifier.Feedback.Service/Program.cs
  src/PullRequestQuantifier.Feedback.Service/PullRequestQuantifier.Feedback.Service.csproj
  src/PullRequestQuantifier.Feedback.Service/Registrar.cs
  src/PullRequestQuantifier.Feedback.Service/appsettings.json
  src/PullRequestQuantifier/PullRequestQuantifier.cs
Labels: Large, Medium

#115 Add [ExcludeFromCodeCoverage]
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifierResultExtensionsTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/Controllers/GitHubWebhookEndpointTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/ConfigurationBuilderExtensions.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/GitHubClientTestServer.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/InMemoryEventBus.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/TestServer/ObjectExtensions.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Controllers/GitHubWebhookController.cs
  src/Tools/PullRequestQuantifier.Tools.CloneAdoRepo/Program.cs
  src/Tools/PullRequestQuantifier.Tools.Common/CommandLine.cs
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/Program.cs
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/PullRequestQuantifier.Tools.QuantifyRepositories.csproj
Labels: Extra Small

#119 Add microsoft form for feedback
  .github/workflows/feedback_service.yml
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifierResultExtensionsTests.cs
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierResultExtensions.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/PullRequestEventHandler.cs
  src/PullRequestQuantifier.Feedback.Service/Controllers/FeedbackController.cs
  src/PullRequestQuantifier.Feedback.Service/Models/FeedbackForm.cs
  src/PullRequestQuantifier.Feedback.Service/PullRequestQuantifier.Feedback.Service.csproj
  src/PullRequestQuantifier.Feedback.Service/Registrar.cs
  src/PullRequestQuantifier.Feedback.Service/appsettings.Development.json
  src/PullRequestQuantifier.Feedback.Service/appsettings.json
Labels: Small

#120 Fix broken feedback link
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierResultExtensions.cs
Labels: Extra Small

#121 Review and Update of README.md
  README.md
Labels: No Changes

#122 Remove *.md exclusion from default context
  src/Clients/PullRequestQuantifier.Client/ContextGenerator/DefaultContext.cs
  src/Clients/PullRequestQuantifier.GitHub.Client.Tests/PullRequestQuantifier.GitHub.Client.Tests.csproj
Labels: Extra Small

#123 Allow FilePath, FileExtension to be set, in ADO we get the diff by creating the fake repo, so we need to set those 2 afterwords
  src/PullRequestQuantifier.Abstractions/Git/GitFilePatch.cs
Labels: Extra Small

#124 remove missleading comment in README "(Avoid clutter)"
  README.md
Labels: No Changes

#129 Add coverage with codecov
  .github/workflows/build_net.yml
  .github/workflows/build_net_core.yml
  .github/workflows/github_client.yml
Labels: Extra Small

#131 Show file path if no extension in the file
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifierResultExtensionsTests.cs
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierResultExtensions.cs
Labels: Extra Small

#130 GitHub - remove previous labels if different
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/PullRequestEventHandler.cs
  src/Clients/PullRequestQuantifier.GitHub.Common/GitHubClient/GitHubClientAdapter.cs
  src/Clients/PullRequestQuantifier.GitHub.Common/GitHubClient/IGitHubClientAdapter.cs
Labels: Extra Small, client: github

#134 Add ideal/non-ideal comments based on result
  src/Clients/PullRequestQuantifier.Client.Tests/Data/AssertCommentSummaryCollapsed.txt
  src/Clients/PullRequestQuantifier.Client.Tests/Data/AssertCommentSummaryNotCollapsed.txt
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifierResultExtensionsTests.cs
  src/Clients/PullRequestQuantifier.Client/Extensions/MarkdownCommentOptions.cs
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierComment.mustache
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierResultExtensions.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/PullRequestEventHandler.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Registrar.cs
  src/PullRequestQuantifier.Abstractions/Core/QuantifierResult.cs
  src/PullRequestQuantifier/PullRequestQuantifier.cs
Labels: Medium

#135 Update idealUpperPercentile to 65, upper bound should always ideal go bellow large
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifierResultExtensionsTests.cs
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierResultExtensions.cs
Labels: Extra Small

#136 Fix issue with local tool parallelization
  src/PullRequestQuantifier.GitEngine/Extensions/PatchExtensions.cs
  src/PullRequestQuantifier.GitEngine/GitEngine.cs
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/Program.cs
Labels: Medium

#137 Adjust upper boundideal to be 60 percentile, this value for the default context will go up to 200 lines changes
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifierResultExtensionsTests.cs
  src/Clients/PullRequestQuantifier.Client/Extensions/QuantifierResultExtensions.cs
Labels: Extra Small

#139 Make PullRequestQuantifier.Tools.QuantifyRepositories to work withouth cloning and run for a repo
  src/Tools/PullRequestQuantifier.Tools.Common/CommandLine.cs
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/Program.cs
  src/Tools/PullRequestQuantifier.Tools.QuantifyRepositories/Properties/launchSettings.json
Labels: Medium

#140 Update Repository stats service
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/InstallationEventHandler.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/InstallationRepositoriesEventHandler.cs
  src/Clients/PullRequestQuantifier.GitHub.Client/Events/PullRequestEventHandler.cs
  src/Clients/PullRequestQuantifier.GitHub.Common/GitHubClient/GitHubClientAdapter.cs
  src/Clients/PullRequestQuantifier.GitHub.Common/GitHubClient/IGitHubClientAdapter.cs
  src/PullRequestQuantifier.Feedback.Service/Controllers/FeedbackController.cs
  src/PullRequestQuantifier.Repository.Service/Events/InstallationEventHandler.cs
  src/PullRequestQuantifier.Repository.Service/Events/InstallationRepositoriesEventHandler.cs
  src/PullRequestQuantifier.Repository.Service/PullRequestQuantifier.Repository.Service.csproj
Labels: Small

#141 Fix the build
  src/PullRequestQuantifier.Repository.Service/Registrar.cs
Labels: Extra Small

#142 Add cloning of repos to repository service
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifierResultExtensionsTests.cs
  src/Clients/PullRequestQuantifier.Client.Tests/QuantifyClientTests.cs
  src/Clients/PullRequestQuantifier.GitHub.Common/GitHubClient/GitHubClientAdapter.cs
  src/Clients/PullRequestQuantifier.GitHub.Common/GitHubClient/IGitHubClientAdapter.cs
  src/PullRequestQuantifier.Common.Tests/GitRepoTestHelpers.cs
  src/PullRequestQuantifier.Common/Azure/BlobStorage/AzureBlobSettings.cs
  src/PullRequestQuantifier.Common/Extensions/FileSystemExtensions.cs
  src/PullRequestQuantifier.Common/PullRequestQuantifier.Common.csproj
  src/PullRequestQuantifier.Feedback.Service/AppConfiguration.cs
  src/PullRequestQuantifier.Feedback.Service/Registrar.cs
  src/PullRequestQuantifier.GitEngine.Tests/GitEngineTests.cs
  src/PullRequestQuantifier.Repository.Service/AppConfiguration.cs
  src/PullRequestQuantifier.Repository.Service/Events/InstallationEventHandler.cs
  src/PullRequestQuantifier.Repository.Service/Properties/launchSettings.json
  src/PullRequestQuantifier.Repository.Service/PullRequestQuantifier.Repository.Service.csproj
  src/PullRequestQuantifier.Repository.Service/Registrar.cs
Labels: Medium

#143 Quantify repositories and push raw commit stats to blob
  src/PullRequestQuantifier.Feedback.Service/Properties/launchSettings.json
  src/PullRequestQuantifier.Repository.Service/Events/InstallationEventHandler.cs
  src/PullRequestQuantifier.Repository.Service/Models/CommitStats.cs
  src/PullRequestQuantifier.Repository.Service/Models/CommitStatsMap.cs
  src/PullRequestQuantifier.Repository.Service/Properties/launchSettings.json
  src/PullRequestQuantifier.Repository.Service/PullRequestQuantifier.Repository.Service.csproj
Labels: Small
